-- Migration: add ShareLink, UploadSession, DownloadSession tables
-- Generated by manual plan

CREATE TABLE "upload_sessions" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "device_id" TEXT NOT NULL,
  "relative_path" TEXT NOT NULL,
  "total_chunks" INTEGER NOT NULL,
  "received_chunks" INTEGER NOT NULL DEFAULT 0,
  "checksum" TEXT,
  "expires_at" TIMESTAMP NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "download_sessions" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "device_id" TEXT NOT NULL,
  "relative_path" TEXT NOT NULL,
  "token" TEXT UNIQUE NOT NULL,
  "expires_at" TIMESTAMP NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "share_links" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "file_id" TEXT NOT NULL,
  "token" TEXT UNIQUE NOT NULL,
  "password_hash" TEXT,
  "expires_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "read_only" BOOLEAN NOT NULL DEFAULT true,
  FOREIGN KEY ("file_id") REFERENCES "file_metadata"("id") ON DELETE SET NULL
);
